### ISSUE TITLE
[crash] node would not ------- npm start ------- even after updating to ver 10.x

### ISSUE THREAD

**Issue by armaanfarshori** [aiitamity/node_backend#6]
0 info it worked if it ends with ok
1 verbose cli [ '/snap/node/1660/bin/node',
1 verbose cli   '/snap/node/1660/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (/snap/node/1660/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /snap/node/1660/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /snap/node/1660/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /snap/node/1660/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/snap/node/1660/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/snap/node/1660/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/snap/node/1660/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /snap/node/1660/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /snap/node/1660/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /home/af/project AK/node_backend
6 verbose Linux 4.15.0-45-generic
7 verbose argv "/snap/node/1660/bin/node" "/snap/node/1660/bin/npm" "start"
8 verbose node v10.15.1
9 verbose npm  v6.4.1
10 error missing script: start
11 verbose exit [ 1, true ]

**Comment by drenther** [comment]
Fixed by #7
